/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chinaso_addnative_Register */

#ifndef _Included_com_chinaso_addnative_Register
#define _Included_com_chinaso_addnative_Register
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chinaso_addnative_Register
 * Method:    staticRegister
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinaso_addnative_Register_staticRegister
  (JNIEnv *, jclass);

/*
 * Class:     com_chinaso_addnative_Register
 * Method:    dynamicRegister
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinaso_addnative_Register_dynamicRegister
  (JNIEnv *, jclass);

/*
 * Class:     com_chinaso_addnative_Register
 * Method:    dynamic_Register1
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinaso_addnative_Register_dynamic_1Register1
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
